version: '3.8'
services:
  postgres:
    image: postgres:15.6
    restart: always
    environment:
      - POSTGRES_USER=jcvegab
      - POSTGRES_PASSWORD=random_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
