version: '3.8'
services:
  pg_db:
    image: postgres:15.6
    restart: always
    environment:
      - POSTGRES_USER=jcvegab
      - POSTGRES_PASSWORD=random_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  users_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'npm run prisma:prepare'
    container_name: conversia-api
    ports:
      - '5000:8080'
    environment:
      - PORT=${PORT}
      - DATABASE_URL=postgresql://jcvegab:random_password@pg_db:5432/postgres?schema=public
      - PASSWORD_SALT=${PASSWORD_SALT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - pg_db
    volumes:
      - ./src:/app/src
volumes:
  pgdata:
